apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tracing
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - https://grafana.github.io/helm-charts
  destinations:
    - namespace: tracing
      server: "{{ .Values.env.development.url }}"
