apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tracing
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  destinations:
    - namespace: vault
      server: https://kubernetes.default.svc
