apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"creationTimestamp":null,"name":"grafana"},"spec":{},"status":{}}
  creationTimestamp: "2025-07-14T08:07:08Z"
  labels:
    kubernetes.io/metadata.name: grafana
  name: grafana
  resourceVersion: "1323"
  uid: dcb9977d-81ef-4af9-9c5d-5ef2e3dcbe8c
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
