apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters:
      selector:
        matchLabels:
          argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: "{{.name}}-apps"
      namespace: argocd
    spec:
      destination:
        namespace: argocd
        name: in-cluster
      project: default
      source:
        helm:
          valuesObject:
            name: "{{.name}}"
        path: manifests
        repoURL: https://github.com/larkintuckerllc/app-of-apps
        targetRevision: 0.1.3
      syncPolicy:
          automated:
            allowEmpty: true
            prune: true
            selfHeal: true 