apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tempo
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: test
            url: "{{ .Values.env.test.url }}"
  template:
    metadata:
      name: "tempo-{{ "{{" }}cluster{{ "}}" }}"
      namespace: argocd
      annotations:
        argocd.argoproj.io/sync-wave: "-5"  # Ensure this is synced after Tempo and before other tracing components
    spec:
      project: tracing
      source:
        repoURL: "https://github.com/selcuksan/kubernetes-cluster-bootstrapping.git"
        targetRevision: HEAD
        path: environments/{{ "{{" }}cluster{{ "}}" }}/tracing-stack/
      destination:
        server: "{{ "{{" }}url{{ "}}" }}"
        namespace: tracing
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 30s
        