apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tracing
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - https://grafana.github.io/helm-charts
    - https://github.com/selcuksan/kubernetes-cluster-bootstrapping.git
  destinations:
    - namespace: tracing
      server: "{{ .Values.env.test.url }}"
    - namespace: operators
      server: "{{ .Values.env.test.url }}"
