apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: logging
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - https://grafana.github.io/helm-charts
  destinations:
    - namespace: logging
      server: "{{ .Values.env.test.url }}"
