apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: alloy
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: test
        url: '{{ .Values.env.test.url }}'
  template:
    metadata:
      name: 'alloy-{{ "{{" }}cluster{{ "}}" }}'
      namespace: argocd
    spec:
      project: alloy
      sources:
        - repoURL: https://grafana.github.io/helm-charts
          chart: alloy
          targetRevision: 1.1.0
          helm:
            valueFiles:
              - $values/environments/{{ "{{" }}cluster{{ "}}" }}/alloy/alloy-values.yaml
        - repoURL: 'https://github.com/selcuksan/kubernetes-cluster-bootstrapping.git'
          targetRevision: HEAD
          ref: values
      destination:
        server: '{{ "{{" }}url{{ "}}" }}'
        namespace: alloy
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true