apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitoring
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - https://prometheus-community.github.io/helm-charts
    - https://grafana.github.io/helm-charts
    - https://github.com/selcuksan/kubernetes-cluster-bootstrapping.git
  sourceNamespaces:
    - argocd
  destinations:
    - namespace: monitoring
      server: "{{ .Values.env.test.url }}"
    - namespace: kube-system
      server: "{{ .Values.env.test.url }}"
