apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: grafana-for-monitoring
  # This ApplicationSet is for Grafana that is used to visualize monitoring data.
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: test
            url: "{{ .Values.env.test.url }}"
  template:
    metadata:
      name: 'grafana-for-monitoring-{{ "{{" }}cluster{{ "}}" }}'
      namespace: argocd
    spec:
      project: monitoring
      sources:
        - repoURL: https://grafana.github.io/helm-charts
          chart: grafana
          targetRevision: 9.2.9
          helm:
            valueFiles:
              - $values/environments/{{ "{{" }}cluster{{ "}}" }}/monitoring-stack/grafana-values.yaml
        - repoURL: "https://github.com/selcuksan/kubernetes-cluster-bootstrapping.git"
          targetRevision: HEAD
          ref: values
      destination:
        server: '{{ "{{" }}url{{ "}}" }}'
        namespace: monitoring
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
